### PR TITLE
all test case pass if run individually

### PR DESCRIPTION
**Pull request by hakrsh**
When I run all the test cases at once it showing segmentation error 
But individually they are perfect

### CODE REVIEW

**Comment by hakrsh** [comment]
So, what do I need to do? Still getting that segmentation fault

**Comment by athul** [comment]
Possibly null pointer refrencing.

**Comment by athul** [comment]
> So, what do I need to do? Still getting that segmentation fault

After all submissions we'll contact you.

**Comment by hakrsh** [comment]
ok

**Pull request closed without merging**
