### PR TITLE
Create acronym

### PR DESCRIPTION
**Pull request by riya-sha**

### CODE REVIEW

**Comment by athul** [comment]
Please save the file with a `.c` extension

**Review by riya-sha — COMMENTED** [review]
changed it

**Comment by riya-sha** [comment]
I changed the filename.But it still show the error.I am new to github so i
dont know how to fix it.

**Comment by athul** [comment]
```
src/acronym.c:16:25: error: incompatible integer to pointer conversion passing 'int' to parameter of type 'const char *'
      [-Werror,-Wint-conversion]
             strcat(abv,toupper((ph[i+1])));
                        ^~~~~~~~~~~~~~~~~~
```
This is the error log I got

**Comment by athul** [comment]
Please save the file in `src/acronym.c`

**Pull request closed without merging**
