### PR TITLE
Update acronym.c

### PR DESCRIPTION
**Pull request by nandakishormpai**
I have added the code for generating Acronyms of Long names inputted

### CODE REVIEW

**Comment by nandakishormpai** [comment]
my code doesn't have error. but warnings are treared as errors
what to do?

**Comment by athul** [comment]
Try to resolve that too. Try one more push as a comment for the CI to work

**Comment by athul** [comment]
You should update the acronym.h as in the commit 9aa160a

**Comment by nandakishormpai** [comment]
I didn't get what you are saying. I am new to GitHub. what should I do with acronym.h and push?

**Comment by athul** [comment]
Update the `acronym.h` file with these lines 
```c
#ifndef ACRONYM_H
#define ACRONYM_H

char *abbreviate(const char *phrase);

#endif
```

**Comment by nandakishormpai** [comment]
I have updated both acronym.c and .h still there are issue it seems. Can you help?

**Review by athul — COMMENTED** [review]
The code is working. Thats fine for now. But if more users get a CI full pass, then we'll have to scrutinize

**Comment by nandakishormpai** [comment]
thank you. can I update my code later if I get a better solution?

**Comment by athul** [comment]
sure.you've got till midnight today

**Pull request closed without merging**
